#!/bin/sh
### BEGIN INIT INFO
# Provides:          raspi-config
# Required-Start: udev mountkernfs $remote_fs
# Required-Stop:
# Default-Start: S
# Default-Stop:
# Short-Description: Switch to ondemand cpu governor (unless shift key is pressed)
# Description:
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
  start)
      # printf " Switching to ondemand scaling governor"
      # SYS_CPUFREQ_GOVERNOR=/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
      # echo "ondemand" > $SYS_CPUFREQ_GOVERNOR

      #echo 0 > /sys/class/vtconsole/vtcon1/bind
      #tvservice -o && tvservice -p
      #sleep 0.1

      /root/wifibroadcast_status/wbc_status "EZ-WifiBroadcast 1.6 RC6" 2 30 1 &

      log_end_msg 0
    ;;
  stop)
    ;;
  restart)
    ;;
  force-reload)
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
