#!/bin/sh -e
#
# udev script to keep Acrux gamepads alive

fix_in_kernel() {
	local version
	if [ "$1" ]; then
		version="$1"
	else
		version="$(uname -r)"
	fi

	case "$version" in
		2.[012345].*|2.6.[0-9]|2.6.[0-9][!0-9]*) return 1 ;;
		2.6.[12][0-9]|2.6.[12][0-9][!0-9]*) return 1 ;;
		2.6.3[012345678]|2.6.3[012345678][!0-9]*) return 1 ;;
	esac
	return 0
}

(
	fix_in_kernel || (while [ -c $1 ]; do sleep 3600 < $1; done)
) &
